# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(),
        ),
    ]
