# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0003_auto_20171107_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_tags',
            field=models.ManyToManyField(related_name='_userprofile_default_tags_+', to='volunteerapp.Tag'),
        ),
    ]
