# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('volunteerapp', '0004_userprofile_default_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteerapp.ProjectCategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('tags', models.ManyToManyField(to='volunteerapp.Tag')),
                ('volunteers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(to='volunteerapp.Project'),
        ),
    ]
