# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0005_auto_20171110_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='volunteerapp.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(blank=True, to='volunteerapp.Project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_tags',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_default_tags_+', to='volunteerapp.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='karma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
