# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0006_auto_20171110_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=140),
            preserve_default=False,
        ),
    ]
