# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteerapp', '0009_auto_20171110_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromEmail', models.CharField(max_length=500)),
                ('toEmail', models.CharField(max_length=500)),
                ('emailBCC', models.TextField()),
                ('emailSubject', models.CharField(max_length=250)),
                ('emailBody', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteerapp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='participation',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
