# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteerapp', '0010_auto_20171110_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldStars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', related_query_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarder', related_query_name='awarder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
