# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('volunteerapp', '0011_goldstars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descrip', models.TextField()),
                ('gpsCoord', models.CharField(max_length=2500)),
                ('address', models.CharField(max_length=500)),
                ('hours', models.CharField(max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
