# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteerapp', '0012_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('awarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_gold_stars', related_query_name='awarded_gold_stars', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_gold_stars', related_query_name='my_gold_stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='goldstars',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='goldstars',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(related_name='projects', related_query_name='projects', to='volunteerapp.Location'),
        ),
        migrations.DeleteModel(
            name='GoldStars',
        ),
    ]
